### ISSUE TITLE
error while obfuscating luau

### ISSUE THREAD

**Issue by ghost** [kosuke14/ByteLuaObfuscator#12]
![image](https://github.com/kosuke14/ByteLuaObfuscator/assets/110673924/8cf0a77d-fc73-4e25-a0a7-a399e940d015)

**Comment by kosuke14** [comment]
this is a lua syntax error.
check your script to obfuscate is ok.

**Comment by kosuke14** [comment]
Luau is not supported.

**Comment by ghost** [comment]
i managed to fix it in the end, thanks
