### ISSUE TITLE
CLI 

### ISSUE THREAD

**Issue by ImInTheICU** [kosuke14/ByteLuaObfuscator#3]
Can you make this CLI
`lua cli.lua --setting true/false --settings2 true/false`
So i can make this interreact with my python-script

**Comment by ImInTheICU** [comment]
Clarify i want to add this into a discord bot

**Comment by kosuke14** [comment]
ok

**Comment by ImInTheICU** [comment]
> ok

Thankssss cant wait to add this to my bot!!!
Love this project!

**Comment by kosuke14** [comment]
done

**Comment by ImInTheICU** [comment]
> done

Thanks
