### ISSUE TITLE
Hello! (Read Me!)

### ISSUE THREAD

**Issue by ImInTheICU** [kosuke14/ByteLuaObfuscator#5]
Hello, do you have plans on making the obfuscation any better or allowing larger file sizes I have people wanting to obfuscate 2mb files but its crashing my bot.

こんにちは、難読化を改善するか、より大きなファイル サイズを許可する計画はありますか? 2 MB のファイルを難読化したい人がいますが、ボットがクラッシュします。

**Comment by kosuke14** [comment]
Try using binary version of v1.2. (In releases)

**Comment by kosuke14** [comment]
Fixed in v1.3
